version: '3.8'

services:
  mysql-service:
    image: mysql:8.4
    container_name: <Msqladmin>
    environment:
      MYSQL_ROOT_PASSWORD: <root>
      MYSQL_DATABASE: <MYSQL>
      MYSQL_USER: <root>
      MYSQL_PASSWORD: <root>
    volumes:
      - <valor>:<valor>
    networks:
      - <valor>
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 30s

  wordpress-service:
    image: wordpress:6
    container_name: <WORDPRESS>
    ports:
      - <8080>:<80>
    environment:
      WORDPRESS_DB_HOST: <root>
      WORDPRESS_DB_USER: <root>
      WORDPRESS_DB_PASSWORD: <root>
      WORDPRESS_DB_NAME: <WORDPRESS>
    volumes:
      - <valor>:<valor>
    networks:
      - <valor>
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 50s
    restart: <valor>
    depends_on:
      mysql-service:
        condition: <valor>
volumes:
  mysql-data:
  wordpress-vol:

networks:
  net-wp:
    driver: bridge
